"""
utils/rag_pipeline.py
----------------------
This module handles STEP 4 of the RAG pipeline: taking the relevant chunks
that FAISS retrieved and feeding them, together with the user's question,
into Google's Gemini LLM so it can generate a grounded, accurate answer.

"RAG" = Retrieval-Augmented Generation:
    Retrieval  -> FAISS finds relevant chunks (done in vector_store.py)
    Augmented  -> we ADD those chunks into the prompt as context
    Generation -> Gemini reads the context and generates the final answer
"""

from langchain_google_genai import ChatGoogleGenerativeAI  # wraps Gemini's chat/completion model for LangChain
from langchain_core.documents import Document  # standard document object (text + metadata) # standard document object (text + metadata)

import config  # our settings file (API key, model name)


# ---------------------------------------------------------------------------
# PROMPT TEMPLATE
# ---------------------------------------------------------------------------
# This template tells Gemini exactly how to behave: answer ONLY using the
# provided context, and admit it when the answer isn't in the PDF (this
# reduces hallucination, a common LLM problem).
PROMPT_TEMPLATE = """
You are a helpful assistant that answers questions using ONLY the context
provided below, which was extracted from a PDF document.

Rules:
- If the answer is not present in the context, say "I could not find this information in the document."
- Do not make up information that isn't supported by the context.
- Keep your answer clear and concise.

Context from the PDF:
----------------------
{context}
----------------------

Question: {question}

Answer:
"""


def get_llm() -> ChatGoogleGenerativeAI:
    """
    Creates and returns the Gemini chat model we use to generate answers.

    Returns
    -------
    ChatGoogleGenerativeAI : the LLM instance
    """
    return ChatGoogleGenerativeAI(
        model=config.GEMINI_CHAT_MODEL,        # which Gemini chat model to call (set in config.py)
        google_api_key=config.GOOGLE_API_KEY,  # our API key
        temperature=0.2,                       # low temperature = more focused / less "creative" answers
    )


def format_context(chunks: list[Document]) -> str:
    """
    Joins the text of all retrieved chunks into a single string, separated
    by blank lines, so it can be inserted into the prompt template.

    Parameters
    ----------
    chunks : list[Document] : the top-k chunks returned by FAISS

    Returns
    -------
    str : all chunk texts concatenated together
    """
    # chunk.page_content holds the actual text of each chunk.
    return "\n\n".join(chunk.page_content for chunk in chunks)


def generate_answer(question: str, retrieved_chunks: list[Document]) -> str:
    """
    The main RAG function: builds the final prompt (context + question)
    and asks Gemini to generate an answer.

    Parameters
    ----------
    question : str : the user's question, typed into the Streamlit UI
    retrieved_chunks : list[Document] : relevant chunks found by FAISS

    Returns
    -------
    str : Gemini's generated answer
    """
    context_text = format_context(retrieved_chunks)  # merge all retrieved chunks into one context block

    # Fill in the prompt template with our actual context and question.
    final_prompt = PROMPT_TEMPLATE.format(context=context_text, question=question)

    llm = get_llm()  # get a Gemini chat model instance

    # .invoke() sends the prompt to Gemini and returns a response object.
    response = llm.invoke(final_prompt)

    # response.content holds the plain text answer generated by the model.
        # NOTE: Depending on the langchain-google-genai version, response.content
    # can either be a plain string, OR a list of content blocks like
    # [{"type": "text", "text": "..."}] (similar to multimodal chat APIs).
    # This handles both formats safely so we always return clean text.
    content = response.content

    if isinstance(content, str):
        # Older/simple format: content is already the answer text.
        return content

    if isinstance(content, list):
        # Newer format: content is a list of blocks; pull out the "text" blocks
        # and join them together in case there are multiple.
        text_parts = [
            block.get("text", "")
            for block in content
            if isinstance(block, dict) and block.get("type") == "text"
        ]
        return "\n".join(text_parts).strip()

    # Fallback: just stringify whatever we got, so the app never crashes.
    return str(content)
